
project_id = "ivndgetmkcwapmttsbqa"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.telegram-bot]
verify_jwt = false
