
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivndgetmkcwapmttsbqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2bmRnZXRta2N3YXBtdHRzYnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNzkyOTksImV4cCI6MjA1NTk1NTI5OX0.NWD55D_pTuf7Ddk_8mZJBtsZg7dsPaVVVJ5e8wpZzMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure the redirect URL for auth redirects
const options = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    redirectTo: `${window.location.origin}/auth?tab=signin`
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, options);

